## \file ekf_local.yaml
## \brief Configurazione EKF locale (odom->base_link) con fusione encoders + IMU
## \details Pubblica /odometry/local e la TF odom->base_link. Nessun ingresso GPS.
ekf_local_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Inputs
    odom0: /diff_drive_controller/odom
    odom0_differential: false
    odom0_queue_size: 10
    # x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  true,
                   false, false, true,
                   false, false, false]

    imu0: /imu/data
    imu0_differential: false
    imu0_queue_size: 50
    imu0_remove_gravity: true
    # x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    imu0_config:  [false, false, false,
                   true,  true,  true,
                   false, false, true,
                   false, false, true,
                   true,  true,  true]

    # General
    sensor_timeout: 0.1
    reset_on_time_jump: true
    print_diagnostics: true
