# Bridge configuration for lawn_mower_robot
# Aligns with diff_drive_robot but removes lidar scan bridge

# Clock from Gazebo -> ROS 2
- ros_topic_name: "clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Joint states from Gazebo -> ROS 2
- ros_topic_name: "joint_states"
  gz_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Odometry from DiffDrive -> ROS 2
- ros_topic_name: "odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# TF poses from Gazebo -> ROS 2
- ros_topic_name: "tf"
  gz_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# Velocity command from ROS 2 -> Gazebo DiffDrive plugin
- ros_topic_name: "cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# IMU from Gazebo -> ROS 2
- ros_topic_name: "imu/data"
  gz_topic_name: "/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Camera
- gz_topic_name: "/camera/image"
  ros_topic_name: "camera/image_raw"
  gz_type_name: "gz.msgs.Image"
  ros_type_name: "sensor_msgs/msg/Image"
  direction: GZ_TO_ROS

- gz_topic_name: "/camera/camera_info"
  ros_topic_name: "camera/camera_info"
  gz_type_name: "gz.msgs.CameraInfo"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  direction: GZ_TO_ROS

# Sonars (LaserScan -> LaserScan)
- gz_topic_name: "/sonar/left/scan"
  ros_topic_name: "sonar/left/scan"
  gz_type_name: "gz.msgs.LaserScan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  direction: GZ_TO_ROS

- gz_topic_name: "/sonar/center/scan"
  ros_topic_name: "sonar/center/scan"
  gz_type_name: "gz.msgs.LaserScan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  direction: GZ_TO_ROS

- gz_topic_name: "/sonar/right/scan"
  ros_topic_name: "sonar/right/scan"
  gz_type_name: "gz.msgs.LaserScan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  direction: GZ_TO_ROS

# GPS
- gz_topic_name: "/gps/fix"
  ros_topic_name: "gps/fix"
  gz_type_name: "gz.msgs.NavSat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  direction: GZ_TO_ROS

