camera:
  ros__parameters:
    camera_id: "/base/axi/pcie@120000/rp1/i2c@80000/ov5647@36"
    width: 640
    height: 480
    framerate: 15
    frame_id: "camera"
    use_sensor_data_qos: true
    qos_overrides:
      "/image_raw":
        reliability: "reliable"
        depth: 10
    # Parametri di calibrazione camera
    camera_info_url: "file:///home/ubuntu/mower/mower_ws/src/mower_bringup/config/camera_info.yaml"
