<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <right_joint>right_wheel_joint</right_joint>
      <left_joint>left_wheel_joint</left_joint>

      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>

      <max_linear_acceleration>2.0</max_linear_acceleration>
      <max_angular_acceleration>4.0</max_angular_acceleration>

      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
      <odom_publisher_frequency>100</odom_publisher_frequency>

      <tf_topic>/tf</tf_topic>
    </plugin>

    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
      <joint_name>right_wheel_joint</joint_name>
      <joint_name>left_wheel_joint</joint_name>
    </plugin>

    <!-- IMU sensor -->
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu">
      <topic>imu</topic>
      <frame_id>base_link</frame_id>
      <update_rate>100</update_rate>
    </plugin>
    
    <!-- Sensori Gazebo: necessario per attivare la pipeline dei sensori -->
    <!--
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors"/>
    -->
    
    <!-- NavSat Gazebo: sistema GPS -->
    <!--
    <plugin filename="gz-sim-navsat-system" name="gz::sim::systems::NavSat"/>
    -->
  </gazebo>

</robot>
