<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Sonar Left -->
  <joint name="sonar_left_joint" type="fixed">
    <parent link="chassis"/>
    <child link="sonar_left_frame"/>
    <origin xyz="${body_length/2 + 0.01} 0.10 0.0" rpy="0 0 ${pi/6}"/>
  </joint>

  <link name="sonar_left_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.015"/>
      </geometry>
      <material name="sonar_material">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.015"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.05" length="0.02" radius="0.015"/>
  </link>

  <!-- Gazebo: Sonar Left -->
  <gazebo reference="sonar_left_frame">
    <sensor name="sonar_left" type="gpu_lidar">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <topic>/sonar/left/scan</topic>
      <gz_frame_id>sonar_left_frame</gz_frame_id>
      <lidar>
        <scan>
          <horizontal>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.02</min>
          <max>3.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </lidar>
    </sensor>
  </gazebo>

</robot>
