<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Sonar sensors (3 front sensors) -->
  <joint name="sonar_left_joint" type="fixed">
    <parent link="chassis"/>
    <child link="sonar_left_frame"/>
    <origin xyz="${body_length/2 + 0.01} 0.10 0.0" rpy="0 0 ${pi/6}"/>
  </joint>

  <link name="sonar_left_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.015"/>
      </geometry>
      <material name="sonar_material">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.015"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.05" length="0.02" radius="0.015"/>
  </link>

  <joint name="sonar_center_joint" type="fixed">
    <parent link="chassis"/>
    <child link="sonar_center_frame"/>
    <origin xyz="${body_length/2 + 0.01} 0 0.0" rpy="0 0 0"/>
  </joint>

  <link name="sonar_center_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.015"/>
      </geometry>
      <material name="sonar_material">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.015"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.05" length="0.02" radius="0.015"/>
  </link>

  <joint name="sonar_right_joint" type="fixed">
    <parent link="chassis"/>
    <child link="sonar_right_frame"/>
    <origin xyz="${body_length/2 + 0.01} -0.10 0.0" rpy="0 0 -${pi/6}"/>
  </joint>

  <link name="sonar_right_frame">
    <visual>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.015"/>
      </geometry>
      <material name="sonar_material">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <cylinder length="0.02" radius="0.015"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.05" length="0.02" radius="0.015"/>
  </link>

  <!-- Camera -->
  <joint name="camera_joint" type="fixed">
    <parent link="chassis"/>
    <child link="camera_frame"/>
    <origin xyz="${body_length/2 - 0.05} 0 ${body_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <link name="camera_frame">
    <visual>
      <geometry>
        <box size="0.04 0.08 0.06"/>
      </geometry>
      <material name="camera_material">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.08 0.06"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.1" x="0.04" y="0.08" z="0.06"/>
  </link>

  <!-- GPS -->
  <joint name="gps_joint" type="fixed">
    <parent link="chassis"/>
    <child link="gps_frame"/>
    <origin xyz="0 0 ${body_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <link name="gps_frame">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.04"/>
      </geometry>
      <material name="gps_material">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.02" radius="0.04"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.2" length="0.02" radius="0.04"/>
  </link>

  <!-- Sonar Gazebo plugins -->
  <gazebo reference="sonar_left_frame">
    <sensor name="sonar_left" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <topic>/sonar/left/scan</topic>
    </sensor>
  </gazebo>

  <gazebo reference="sonar_center_frame">
    <sensor name="sonar_center" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <topic>/sonar/center/scan</topic>
    </sensor>
  </gazebo>

  <gazebo reference="sonar_right_frame">
    <sensor name="sonar_right" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <topic>/sonar/right/scan</topic>
    </sensor>
  </gazebo>

  <!-- Camera Gazebo plugin -->
  <gazebo reference="camera_frame">
    <sensor name="camera" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <topic>/camera/image</topic>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <camera>
        <horizontal_fov>1.57</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
        <info_topic>/camera/camera_info</info_topic>
      </camera>
      <frame_id>camera_frame</frame_id>
    </sensor>
  </gazebo>

  <!-- GPS Gazebo plugin -->
  <gazebo reference="gps_frame">
    <sensor name="gps" type="navsat">
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <topic>/gps/fix</topic>
      <navsat>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.1</stddev>
        </noise>
      </navsat>
    </sensor>
  </gazebo>

</robot>
