<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- GPS -->
  <joint name="gps_joint" type="fixed">
    <parent link="chassis"/>
    <child link="gps_frame"/>
    <origin xyz="0 0 ${body_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <link name="gps_frame">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.04"/>
      </geometry>
      <material name="gps_material">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.02" radius="0.04"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.2" length="0.02" radius="0.04"/>
  </link>

  <!-- Gazebo: GPS -->
  <gazebo reference="gps_frame">
    <sensor name="gps" type="navsat">
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <topic>/gps/fix</topic>
      <gz_frame_id>gps_frame</gz_frame_id>
      <navsat>
        <position_sensing>
          <horizontal>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.5</stddev>
            </noise>
          </horizontal>
          <vertical>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.0</stddev>
            </noise>
          </vertical>
        </position_sensing>
        <velocity_sensing>
          <horizontal>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.1</stddev>
            </noise>
          </horizontal>
          <vertical>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>0.2</stddev>
            </noise>
          </vertical>
        </velocity_sensing>
      </navsat>
    </sensor>
  </gazebo>

</robot>
