<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- IMU -->
  <joint name="imu_joint" type="fixed">
    <parent link="chassis"/>
    <child link="imu_frame"/>
    <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="imu_frame">
    <visual>
      <geometry>
        <box size="0.03 0.03 0.02"/>
      </geometry>
      <material name="imu_material">
        <color rgba="0.2 0.2 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.03 0.02"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.05" x="0.03" y="0.03" z="0.02"/>
  </link>

  <!-- Gazebo: IMU -->
  <gazebo reference="imu_frame">
    <sensor name="imu" type="imu">
      <always_on>true</always_on>
      <update_rate>50</update_rate>
      <topic>/imu/data</topic>
      <imu>
        <noise type="gaussian">
          <rate>
            <mean>0.0</mean>
            <stddev>0.02</stddev>
          </rate>
          <accel>
            <mean>0.0</mean>
            <stddev>0.1</stddev>
          </accel>
        </noise>
      </imu>
    </sensor>
  </gazebo>

</robot>
