<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Camera -->
  <joint name="camera_joint" type="fixed">
    <parent link="chassis"/>
    <child link="camera_frame"/>
    <origin xyz="${body_length/2 - 0.05} 0 ${body_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <link name="camera_frame">
    <visual>
      <geometry>
        <box size="0.04 0.08 0.06"/>
      </geometry>
      <material name="camera_material">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.08 0.06"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.1" x="0.04" y="0.08" z="0.06"/>
  </link>

  <!-- Gazebo: Camera -->
  <gazebo reference="camera_frame">
    <sensor name="camera" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <topic>/camera/image</topic>
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <camera>
        <horizontal_fov>1.57</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
        <info_topic>/camera/camera_info</info_topic>
      </camera>
      <frame_id>camera_frame</frame_id>
    </sensor>
  </gazebo>

</robot>
